.TH GOSTORE 1 2019-08-07

.SH Name
.PP
gostore - A command-line minimalist media collection manager.

.SH Synopsis
.PP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBhelp\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBversion\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBimport\fP [--\fBauto\fP] [--\fBdry-run\fP] \fImedia\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBinfo\fP [--\fBfrom-file\fP] \fIname\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBlist\fP \fIquery\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBedit\fP \fIname\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBdelete\fP \fIname\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBexport\fP \fIname\fP \fIdst\fP
\fBgostore\fP [--\fBdebug\fP] [--\fBroot\fP=\fIROOT\fP] [--\fBstyle\fP=\fIname|list|full|json\fP] \fBcheck\fP

.SH Description
.PP
A command-line minimalist media collection manager.

.SH Options
.TP
\fB--\fBdebug\fP\fP
Show debug information.
.TP
\fB--\fBroot\fP=\fIROOT\fP\fP
Path to the root of the collection.
.TP
\fB--\fBstyle\fP=\fIname|list|full|json\fP\fP
Style for printing records' details.

.SH Commands
.TP
\fB\fBhelp\fP\fP
Show usage information.
.TP
\fB\fBversion\fP\fP
Show version information.
.TP
\fB\fBimport\fP [<flags>] \fImedia\fP\fP
Import a new media into the collection.
.TP
\fB\fBinfo\fP [<flags>] \fIname\fP\fP
retrieve information about any collection's record.
.TP
\fB\fBlist\fP [\fIquery\fP]\fP
List the the records that match the given query. If no query is provied, list all records
.TP
\fB\fBedit\fP \fIname\fP\fP
edit an existing record from the collection.
.TP
\fB\fBdelete\fP \fIname\fP\fP
delete a record from the collection.
.TP
\fB\fBexport\fP \fIname\fP \fIdst\fP\fP
export a media from the collection to the given destination.
.TP
\fB\fBcheck\fP\fP
Verify collection's consistency.
