.TH GOSTORE 1 "GOSTORE\-1"

.SH Name
.PP
gostore \- A command\-line minimalist media collection manager.

.SH Synopsis
.PP
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBhelp\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBversion\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBimport\fP [\-\-\fBauto\fP] [\-\-\fBdry\-run\fP] \fImedia\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBinfo\fP [\-\-\fBfrom\-file\fP] \fIname\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBlist\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBsearch\fP \fIquery\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBedit\fP \fIname\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBdelete\fP \fIname\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBexport\fP \fIname\fP \fIdst\fP
.br
\fBgostore\fP [\-\-\fBdebug\fP] [\-\-\fBroot\fP=\fIROOT\fP] [\-\-\fBstyle\fP=\fIlist|full|json|name\fP] \fBcheck\fP

.SH Description
.PP
A command\-line minimalist media collection manager.

.SH Options

.TP
\-\-\fBdebug\fP
Show debug information.

.TP
\-\-\fBroot\fP=\fIROOT\fP
Path to the root of the collection.

.TP
\-\-\fBstyle\fP=\fIlist|full|json|name\fP
Style for printing records' details.

.SH Commands

.TP
\fBhelp\fP
Show usage information.

.TP
\fBversion\fP
Show version information.

.TP
\fBimport\fP [<flags>] \fImedia\fP
Import a new media into the collection.

.TP
\fBinfo\fP [<flags>] \fIname\fP
retrieve information about any collection's record.

.TP
\fBlist\fP
List all the records from the collection.

.TP
\fBsearch\fP \fIquery\fP
Search the collection.

.TP
\fBedit\fP \fIname\fP
edit an existing record from the collection.

.TP
\fBdelete\fP \fIname\fP
delete a record from the collection.

.TP
\fBexport\fP \fIname\fP \fIdst\fP
export a media from the collection to the given destination.

.TP
\fBcheck\fP
Verify collection's consistency.
